### ISSUE TITLE
Infinite loading loop

### ISSUE THREAD

**Issue by soerenray** [elliefairholm/on-this-day#3]
Although I configured the main config.js file according to your doc, the MagicMirror is stuck showing the loading sign instead of the "on-this-day-fact". When I looked into the error, it said that "the fact was not callable".
Hope to hear from you, maybe there is something wrong with the API?
Pretty cool project though, love to see the commitment!

**Comment by elliefairholm** [comment]
Hi!

Hmm, how odd, other people say that it works for them. I will definitely
take a look this weekend :)

Can I ask what you put in the main config.js for my module so that I can
replicate it with mine?

**Comment by soerenray** [comment]
`/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out or empty, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "de",
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device

	modules: [
		{
			module: "clock",
			position: "top_left"
		},
		{
			module:"currentweather",
			position:"top_left",
			config: {
				useLocationAsHeader: true,
				updateIntervall: 900000,
				showHumidity: true,
				showWindDirection: false,
				degreeLabel: true,
				showHumidity: true,
				useBeaufort: false,
				roundTemp: true,
				showFeelsLike:false,
				decimalSymbol:",",
				location:"XXXX",
				appid:"XXXXXX",
			}
		},
		{
			module:"on-this-day",
			position:"bottom_bar",
			config:{
				interests:"history",
			}
		},
		{
			module:"MMM-KVV",
			position:"top_right",
			config:{
				stopID:"de:8212:3",
			}
		},
		{
			module:"MMM-BurnIn",
			position:"lower_third",
			config:{
				updateInterval: 15,
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
`

**Comment by soerenray** [comment]
Sorry for the weird formatting, I just copy-pasted it.. I ran npm run config:check in the MagicMirror Folder and it didn't show any syntax errors

**Comment by soerenray** [comment]
devtools shows error in line 158: "unable to get fact"

**Comment by elliefairholm** [comment]
Thanks for sending that!

From the top of my head, I think that interests has to be an array rather
than a string - so rather than putting:

config {
    interests: "history"
}

if you change it to:

config {
    interests: ["history"]
}

I think that should do the trick. If not, do let me know.

I'll still have a look this weekend and try make things clearer :)

**Comment by soerenray** [comment]
My config file now looks like this, but still shows the same error when running npm start dev... 

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out or empty, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "de",
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device

	modules: [
		{
			module: "clock",
			position: "top_left"
		},
		{
			module:"currentweather",
			position:"top_left",
			config: {
				useLocationAsHeader: true,
				updateIntervall: 900000,
				showHumidity: true,
				showWindDirection: false,
				degreeLabel: true,
				showHumidity: true,
				useBeaufort: false,
				roundTemp: true,
				showFeelsLike:false,
				decimalSymbol:",",
				location:"Heltersberg",
				appid:"69806cab7c48c4c84c4c54f6c78bcd52",
			}
		},
		{
			module:"on-this-day",
			position:"bottom_bar",
			config:{
				interests:["history"]
			}
		},
		{
			module:"MMM-KVV",
			position:"top_right",
			config:{
				stopID:"de:8212:3",
			}
		},
		{
			module:"MMM-BurnIn",
			position:"lower_third",
			config:{
				updateInterval: 15,
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by elliefairholm** [comment]
Hello :)

So I figured out what the issue was!

I was using the packing Moment.js as a dependency to format the date, but I
didn't realise that depending on your browser and language configuration,
moment gives you different date formats. I didn't realise that the German
format is 2020.05.11 and not 2020/05/11, and as my code was splitting the
time using '/', it could not properly format the date. This then meant that
when the API was called, as the date format was wrong, the response was
that there was no fact.

I've updated it now though and have tested it with your config file so it
should definitely work for you (but in case it doesn't please do let me
know!).

Sorry that it didn't work in the first place, and hope you're well :)

Ellie

**Comment by soerenray** [comment]
Hi,
it works perfectly! Thanks for the heads up and for the work you put in :)

Soeren

**Comment by soerenray** [comment]
Hi Ellie,
I cloned the repository in another folder on my Raspberry Pi and it, surprisingly, threw the same error. As a result, I (a JS newbie) tried changing the code so it works regardless of your location(in other words: I wouldn't encounter my issue I encountered earlier).. I'll attach it in the next comment, maybe it helps prevent future comlications.

Hope you're well,
Soeren

**Comment by soerenray** [comment]
[on-this-day.txt](https://github.com/elliefairholm/on-this-day/files/4703818/on-this-day.txt)

**Comment by elliefairholm** [comment]
Hello!

Sorry it's taken me so long to reply.

Thank you so much for sending me your code, I really appreciate it. It was
great - I made a few adjustments and uploaded the changes. You're right, it
was much easier to do it that way.

Thanks again for the email, and hope all is well with you :)

Ellie
