### ISSUE TITLE
Heroku API Giving Error

### ISSUE THREAD

**Issue by jordan-martin** [elliefairholm/on-this-day#4]
I've been running this module for a while and a few days ago it started to not show new data, and instead shows "Loading..." in the module space. I went to the URL directly (http://on-this-day-api.herokuapp.com/facts/11-22) and it is showing an application error. I'm assuming something has gone wrong with the API.

**Comment by TheENGR** [comment]
I ran into the same issue

**Comment by Rayvenhaus** [comment]
Still not working, nothing but "Loading" and an error on the application page.

**Comment by elliefairholm** [comment]
hi all, thanks for your interest in this project! i have fixed this issue so if you reload the component you will be able to see the facts.

i'll close this issue for now, but if you see anything else feel free to open a new issue :)
