### ISSUE TITLE
Unable to get API Key

### ISSUE THREAD

**Issue by ebonak** [elliefairholm/on-this-day#5]
The provided link for the free API Key gives error

```
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

```

**Comment by elliefairholm** [comment]
hello, thanks for your comment! i have fixed this issue so you will no longer get this error.

i'll close this issue for now but feel free to open a new one if you find anything :)
