### ISSUE TITLE
Never seems to update

### ISSUE THREAD

**Issue by mlcampbe** [elliefairholm/on-this-day#9]
I'm trying to use the module with the current MM release and it loads and displays a rotating list of events as I was looking for but it never seems to refresh the events for the next day. 

For example, lets say I start MM on Jan 11 and I see a list of events. Then come Jan 12 I still see the same list of events being rotated.

Can you check to see if this is working given the age of your module?

**Comment by elliefairholm** [comment]
thanks for letting me know!

have fixed this issue now and the date properly updates each day at midnight :)
